{% set bootstrapping = os.environ.get('CONDA_BUILD_BOOTSTRAPPING', '') %}
{% set version = "2.8" %}
# Please increment by two
{% set build = 0 %}

package:
  name: patch
  version: {{ version }}

source:
  url:
    - https://ftpmirror.gnu.org/gnu/patch/patch-{{ version }}.tar.gz
    - https://ftp.gnu.org/gnu/patch/patch-{{ version }}.tar.gz
  sha256: 308a4983ff324521b9b21310bfc2398ca861798f02307c79eb99bb0e0d2bf980

build:
  number: {{ build if bootstrapping == 'yes' else build + 1002 }}
  string: h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}{{ '_bootstrapping' if bootstrapping == 'yes' }}
  skip: True  # [win]

requirements:
  build:
{% if bootstrapping != 'yes' %}
    - libtool  # [unix]
{% endif %}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - make

test:
  commands:
    - patch --help
{% if bootstrapping != 'yes' %}
  files:
    - testfile
    - testfile2
    - testfile.patch
{% endif %}

about:
  home: http://savannah.gnu.org/projects/patch/
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: Utility to apply diffs to files
  description: |
    Patch takes a patch file containing a difference listing produced by the
    diff program and applies those differences to one or more original files,
    producing patched versions.
  dev_url: http://git.savannah.gnu.org/cgit/patch.git

extra:
  recipe-maintainers:
    - nehaljwani
    - mgorny
