{% set bootstrapping = os.environ.get('CONDA_BUILD_BOOTSTRAPPING', '') %}
{% set name = "patch" %}
{% set version = "2.7.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://ftp.gnu.org/gnu/patch/patch-{{ version }}.tar.gz
  sha256: 8cf86e00ad3aaa6d26aca30640e86b0e3e1f395ed99f189b06d4c9f74bc58a4e
  patches:
    # taken from https://gitweb.gentoo.org/repo/gentoo.git/tree/sys-devel/patch/patch-2.7.6-r6.ebuild?id=2f52e76ae543f555f598e2e786b434c0610584ca
    # kept original filenames to ease syncing
    - patches/patch-2.7.6-fix-test-suite.patch
    - patches/patch-2.7.6-fix-error-handling-with-git-style-patches.patch
    - patches/patch-2.7.6-CVE-2018-6951.patch
    - patches/patch-2.7.6-allow-input-files-to-be-missing-for-ed-style-patches.patch
    - patches/patch-2.7.6-CVE-2018-1000156.patch
    - patches/patch-2.7.6-CVE-2018-6952.patch
    - patches/patch-2.7.6-Do-not-crash-when-RLIMIT_NOFILE-is-set-to-RLIM_INFINITY.patch
    - patches/patch-2.7.6-CVE-2018-1000156-fix1.patch
    - patches/patch-2.7.6-CVE-2018-1000156-fix2.patch
    - patches/patch-2.7.6-CVE-2019-13636.patch
    - patches/patch-2.7.6-CVE-2019-13638.patch
    - patches/patch-2.7.6-Avoid-invalid-memory-access-in-context-format-diffs.patch
    - patches/patch-2.7.6-configure-mkdir.patch

build:
{% if bootstrapping == 'yes' %}
  # Please increment by two
  number: 2
  string: h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}_bootstrapping
{% else %}
  # Keep above the number of the _bootstrapping package
  number: 1004
  string: h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
{% endif %}
  skip: True  # [win]

requirements:
  build:
{% if bootstrapping != 'yes' %}
    - libtool  # [unix]
{% endif %}
    - {{ compiler('c') }}
    - make

test:
  commands:
    - patch --help
{% if bootstrapping != 'yes' %}
  files:
    - testfile
    - testfile2
    - testfile.patch
{% endif %}

about:
  home: http://savannah.gnu.org/projects/patch/
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: Native Win32 versions of common unix tools
  description: |
    Patch takes a patch file containing a difference listing produced by the
    diff program and applies those differences to one or more original files,
    producing patched versions.
  dev_url: http://git.savannah.gnu.org/cgit/patch.git

extra:
  recipe-maintainers:
    - nehaljwani
